### PR TITLE
Add 'Get Involved'

### PR DESCRIPTION
**Pull request by wbamberg**
Fixes https://github.com/openwebdocs/website/issues/9.

I'm not very good at these types of pages so I'd welcome some input. I did consider having a bit on "Make a project proposal" but I feel like we should have more meta-docs for this before we can do that (describing, for example, what makes a good proposal, and how we assess them, etc).

Also ping @robnyman for any possible improvements (since IIRC he asked for this :).

### CODE REVIEW

**Review by Elchi3 — COMMENTED** [review]
Thanks for getting this started!

I wonder if we should also point to more places where people can get involved or rather read more about us and chat with us?
Random ideas: Link to weekly meeting notes and twitter? Have a section about events where we took/take part in? WTD Prague/Portland.

**Comment by wbamberg** [comment]
> Thanks for getting this started!
> 
> I wonder if we should also point to more places where people can get involved or rather read more about us and chat with us? Random ideas: Link to weekly meeting notes and twitter? Have a section about events where we took/take part in? WTD Prague/Portland.

I'm not too sure what the "involvement" aspect of weekly meeting notes is though, especially as these are not public meetings. Events are a good one though!

**Comment by robnyman** [comment]
Thanks @wbamberg I think this is a good start! Like Florian said, if there are ways of having them connect with us as well – events, chat, Slack etc – I think that would be very good! And/or how to get started on contributing to docs. Maybe have a quick explainer and suggestions?

**Comment by wbamberg** [comment]
I've tried to add something about contributing to MDN (although I think we could do better with this on the MDN end...), and  I did add a bit about openwebdocs/projects.

I've also added something on events. AFAIK we don't have a public chat or Slack so not sure what to put there.

**Review by Elchi3 — APPROVED** [review]
This looks great to me now!

I think an opportunity to publicly chat with us would be great but it's a separate discussion whether and how we would open up our slack, for example. I don't want to block on that now but it is a good discussion to have.

**Comment by Elchi3** [comment]
I asked about opening up our slack in the #community-enablement channel in... slack :)

**Pull request merged**
