### PR TITLE
Add sponsors page

### PR DESCRIPTION
**Pull request by wbamberg**
This PR adds a simple page listing our main sponsors and linking to OpenCollective for the full list.

I have not included logos here at this point because the organizations I have checked seem to want formal brand approval before we include their logo (e.g. https://about.google/brand-resource-center/brand-elements/ ). Perhaps we can ask the our representatives of the organizations to help secure this, then when we have it we can add the logos?

### CODE REVIEW

**Comment by robnyman** [comment]
My first instinct is that logos would indeed be nice. Since we are sponsors I believe using our logo should just be fine (the same that is being displayed at Open Collective).

**Comment by wbamberg** [comment]
I've added sponsor logos. I just copied them from the Open Collect site, I hope that's OK.

**Comment by robnyman** [comment]
@wbamberg I think it might be. Probably worth double-checking with Pia or someone where they come from, but feel fairly certain they are the approved and correct ones.

**Comment by Elchi3** [comment]
Should the list be a table? Or use some other sort of alignment in columns? Would improve readability imo.

**Review by Elchi3 — APPROVED** [review]
Yes! Thanks!

**Pull request merged**
